apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-deployment
  labels:
    app: recipe-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: recipeservice:latest  # Use your Docker image path here, e.g., yourdockerhubusername/recipeservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://your-mongodb-service-name:27017/recipe_db" # Adjust based on your MongoDB service name & config in K8s
          # More environment variables can be added if necessary
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
