apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  labels:
    app: recipe-service
spec:
  selector:
    app: recipe-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP